### PR TITLE
Mon 4719 stalk options changed on modification

### PR DESCRIPTION
**Pull request by bouda1**
# Pull Request Template

## Description

Please include a short resume of the changes and what is the purpose of PR. Any relevant information should be added to help:
* **QA Team** (Quality Assurance) with tests.
* **reviewers** to understand what are the stakes of the pull request.

**Fixes** # (issue)

## Type of change

- [X] Patch fixing an issue (non-breaking change)
- [ ] New functionality (non-breaking change)
- [ ] Breaking change (patch or feature) that might cause side effects breaking part of the Software
- [ ] Updating documentation (missing information, typo...)

## Target serie

- [ ] 18.10.x
- [ ] 19.04.x
- [ ] 19.10.x
- [X] 20.04.x (master)

<h2> How this pull request can be tested ? </h2>

Configure a service with all the notification flags enabled and no stalk flags.

Push the configuration. Then modify the service to change a little thing (not the notification or stalk flags).

Push again the configuration. If the bug is there, you should see in the centreon_storage that stalk
flags are not all set to 0. If the bug is fixed, you should see all the stalk flags set to 0.

With the patched version, you should also test the same steps but with only the unknown flag enabled for the stalks and the critical flag enabled for the notifications or anything else.

The query to check in the database is:
`SELECT stalk_on_critical, stalk_on_ok, stalk_on_unknown, stalk_on_warning FROM services WHERE service_id = <id of service>\G`

### CODE REVIEW

**Comment by CPbN** [comment]
Should then correct https://github.com/centreon/centreon/issues/8259 :)
Many thanks @bouda1 👍

**Comment by bouda1** [comment]
Yes, exactly.
Cheers.

**Comment by SylvestreG** [comment]
can you update release note please :pray:

**Comment by UrBnW** [comment]
I confirm this fixes https://github.com/centreon/centreon/issues/8259, many thx @bouda1 👍

**Pull request merged**
